### ISSUE TITLE
How to install the r2ghidra plugin on Windows

### ISSUE THREAD

**Issue by robinkang63** [radareorg/r2ghidra#29]
Hi, first of all, thanks for this build. you are doing great. but I am running with an issue regarding the installation of ghindra plugin. 
I installed radare2 latest version from windows installer and for plugin as per instruction i unzip it in radare directory but when i try to decode a function, i came up with following error

```
[0x000008a0]> afl
0x000008a0    1 12           entry0
0x00000dac    8 236          sym.Java_sg_vantagepoint_uncrackable2_CodeCheck_bar
0x00000d8c    1 32           sym.Java_sg_vantagepoint_uncrackable2_MainActivity_init
0x00000918   10 220          fcn.00000918
0x000007f0    1 16           sym.imp.pthread_create
0x00000800    1 16           sym.imp.__cxa_finalize
0x00000810    1 16           sym.imp.ptrace
0x00000820    1 16           sym.imp.strncmp
0x00000830    1 16           sym.imp._exit
0x00000840    1 16           sym.imp.__stack_chk_fail
0x00000850    1 16           sym.imp.fork
0x00000860    1 16           sym.imp.getppid
0x00000870    1 16           sym.imp.waitpid
0x00000880    1 16           sym.imp.pthread_exit
0x00000890    1 16           sym.imp.__cxa_atexit
0x000008b0    2 8            entry.fini0
0x000007d0    1 20           fcn.000007d0
[0x000008a0]> s 0x00000dac
[0x00000dac]> pdg
Error: r2pm -ci r2ghidra
```

**Comment by liujz41** [comment]
me too

**Comment by trufae** [comment]
I assume there are some issues loading the plugin, I don't have any windows to try anything, can you set R2_DEBUG=1 env var before calling r2 and see the output when it tries to load it?

**Comment by imprint-extract** [comment]
I have also tried setting up r2ghidra on Windows and have questions that might be relevant here.

On the README.md, it says: 

>You need to build r2 or download it from the last release unzip it under the radare2 directory and then run the build.bat script.
>Alternatively you can download the CI builds from the release page.

I can't locate a build.bat script in the repo, but there is a r2.bat which just runs radare2.exe.
When I downloaded the CI builds, they contained 3 dlls. I wasn't sure if it's what I was meant to do, but I copied them from the zip to my radare2/bin directory.

However, when I re-run radare2.exe and do pdg, it still gives the `Error: r2pm -ci r2ghidra` error.

The file r2pm itself is an extensionless file, which doesn't do anything on Windows. So, running `r2pm -ci r2ghidra` in cmd just gives 
```
'r2pm' is not recognized as an internal or external command,
operable program or batch file.
```

It would help to either have a r2pm.bat which does the plugin install, or some new instructions on what to do with the 3 dll files in the CI build.

Thanks!

**Comment by trufae** [comment]
Correct, that build.bat has been removed a while ago. i just fixed the readme. the only windows i have is the github CI, so i can't really do much testing on this, let me clarify some stuff:

* r2pm is a shellscript, so it's only available on unix systems
* r2env is going to replace r2pm (and support binary packages and windows soon)
* to build r2ghidra on windows i'm using make+cmake+ninja (see the .github/worksflows/ci.yml for more details)
* Using the R2_DEBUG=1 env var you'll see which plugins is r2 trying to load and why it fails to load them
* See in the output of `r2 -hh` the `Plugins:` section to see where the plugins should be placed
* You can load/unload core plugins at runtime using the `L core_ghidra.dll` command
* You can download the latest .dll builds from the CI artifacts
* The core plugin is the one in charge to decompile, the asm and anal ones are used for disasembling and analyzing (when you do `r2 -a r2ghidra `

Can you try this stuff and see if it works? It would be great if you could also contribute and test r2env 

* https://github.com/radareorg/r2env

Also, i have recently replaced the huge ghidra submodule by a tiny repo containing only the c++ code (6MB vs 600MB), which is making it less painful. But i still want to improve it before doing a new release (5.3.1).

Thanks!

**Comment by sordidlist** [comment]
I ran ```r2 -hh``` and created the path listed for user plugins on my Windows VM, then copied in the 3 dlls. Then I ran r2 and was able to successfully launch the Ghidra decompiler.

I'm able to successfully do ```pip install r2env``` on both Ubuntu and Windows. However Windows still doesn't recognize r2env as a valid command after installation, and I'm not quite sure why.

On Ubuntu 21.04, I was able to get as far as:

```
# r2env add radare2
Adding package
Building radare2
Cloning into '/home/.r2env/src/radare2@git'...
remote: Enumerating objects: 232649, done.
remote: Counting objects: 100% (274/274), done.
remote: Compressing objects: 100% (152/152), done.
remote: Total 232649 (delta 145), reused 218 (delta 121), pack-reused 232375
Receiving objects: 100% (232649/232649), 132.71 MiB | 3.04 MiB/s, done.
Resolving deltas: 100% (179389/179389), done.
Building ...
tail -f /home/.r2env/log/radare2.txt
Traceback (most recent call last):
  File "/usr/local/bin/r2env", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/r2env/repl.py", line 177, in main
    if not run_action(e, args.action, args.args):
  File "/usr/local/lib/python3.8/dist-packages/r2env/repl.py", line 143, in run_action
    if not match_pkg(pkgs, targets, add_package):
  File "/usr/local/lib/python3.8/dist-packages/r2env/repl.py", line 96, in match_pkg
    cb(pkg, profile)
  File "/usr/local/lib/python3.8/dist-packages/r2env/repl.py", line 49, in add_package
    pkg.build(profile)
  File "/usr/local/lib/python3.8/dist-packages/r2env/db/radare2.py", line 107, in build
    build_radare2(profile)
  File "/usr/local/lib/python3.8/dist-packages/r2env/db/radare2.py", line 86, in build_radare2
    use_meson = profile["meson"]
KeyError: 'meson'
```

I can try to take a crack at the python this weekend, but figured I'd let you know what I got from testing.

**Comment by trufae** [comment]
@as0ler is working on r2env and he will push the changes as soon as they get stable. You can try `r2env add radare2@git`. but yeah the line you posted should be reported as an issue in r2env, so better move the discussion there.

Good to know that r2ghidra windows builds are working as expected :) can you show the paths displayed by r2-hh and maybe improve the installation instructions from the readme if you find them confusing.

thanks!

**Comment by trufae** [comment]
Added https://github.com/radareorg/r2env/issues/1
